### ISSUE TITLE
Back End: Add second dropoff time model

### ISSUE THREAD

**Issue by shawnadelic** [hackforla/spare#153]
We're going to be adding a second dropoff time model.
This will be for adding specific manual dates, and the other dropoff time will be for recurring/periodic dates (weekly for now).
They will all be returned from the dropoff times endpoint. The only difference will be that they won't be automatically recalculated.
I'll probably just tackle this one.

**Comment by ndanielsen** [comment]
@shawnadelic Assuming that this goes on the `DonationFulfillment` model?

**Comment by shawnadelic** [comment]
Added a ManualDropoffDate model
