### ISSUE TITLE
Donor page - Empty state for there are no donations requested

### ISSUE THREAD

**Issue by calexity** [hackforla/spare#156]
As a potential Spare donor
When I reach the home (aka donor page)
AND if there are no requests in ANY CATEGORY
then I see an empty state making it clear there are no requests.

*Design Notes*
Attached is the design proposal:

It's the image tiles moved up with their labels hidden and the whole set at 20% opacity.
Text over it is Lato (22px for top line, 16px for bottom line) with underlines for the links.

- Ask line goes to Request page
- Learn more goes to our How it works page

InVision link: https://projects.invisionapp.com/d/main#/console/14019621/321502885/preview

![home_emptystate](https://user-images.githubusercontent.com/1103366/45937430-1ccfd580-bf7d-11e8-8be1-58e739b22e60.png)

**Comment by calexity** [comment]
@jrkoch you're my hero! Thank you

**Comment by jrkoch** [comment]
Thank you, let me know if it needs any tweaks!
