### ISSUE TITLE
Update About page with our new, improved copy

### ISSUE THREAD

**Issue by calexity** [hackforla/spare#157]
New language to better describe our project courtesy of @kelseydieterich 
----

"During this homelessness crisis, we believe every gesture of human kindness makes a difference. A jacket not only brings comfort physically but also, it can build a tiny connection that turns a stranger into a friend."

**About:**
Spare connects people in need of clothing and other essentials with people in the community who have things to spare. It's like a one-on-one Goodwill. The main objective is to foster interactions between the housed and unhoused. We’re hoping the donation can be a mechanism for building these connections throughout our community.

**How it works:**
There are two main pages, a donation page and a request page. If you want to donate, the donation page houses each request that comes in, and you can fulfill a specific request from there. If you’d like to request an item, the request page has categories you can fill out a short form to request. Once there is a match both the requester and donator will receive an email and text on when to pick-up/drop-off the item at the designated donation facility. These locations are well known established donation facilities, already in use for general donations.

**The team:**
We’re a small team of volunteers with Hack for LA. You can contribute to our [Github project](https://github.com/hackforla/spare) or [find us on Slack](hackforla.org/slack). You can also email us at [team@whatcanyouspare.org](mailto:team@whatcanyouspare.org) but keep in mind that we're volunteers and may be slow to respond.

**Comment by rbhenao** [comment]
Seems to be implemented already. Closing this.
