### ISSUE TITLE
Change request form language

### ISSUE THREAD

**Issue by shawnadelic** [hackforla/spare#161]
Above our request form we have the following:

> We send your name and contact info to the person who wants to donate.
> We don't post it on our site.

We need to remove the part about sharing contact info (since we won't be)

**Comment by calexity** [comment]
Shawn, you are the best. Tireless!

**Comment by shawnadelic** [comment]
Changed this language to this:

> All donation requests are listed anonymously on our site.
> Your contact info is used to send updates about your request.
