### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by calexity** [hackforla/spare#169]
Add GA so we can see traffic and info about visits

Instructions from Google: Copy and paste this code as the first item into the <HEAD> of every webpage you want to track. More info: https://support.google.com/analytics/answer/7538414

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125629315-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125629315-1');
</script>
```

**Comment by ndanielsen** [comment]
@Allicolyer is going to do this!
