### ISSUE TITLE
Front end - Use image SVGs instead of PNGs so our site doesn't look blurry

### ISSUE THREAD

**Issue by calexity** [hackforla/spare#178]
Right now, all of the icons are looking blurry. This ticket is to replace them with the SVGs or if that's not easy, use the @2x or @3x PNGs.

All assets are in the public assets folder under "tiles"

**Comment by calexity** [comment]
@ndanielsen This looks beautiful! Can I close this ticket?

**Comment by ndanielsen** [comment]
Yup all is good to close
