### ISSUE TITLE
Show all items on donate and request pages

### ISSUE THREAD

**Issue by pmfabel** [hackforla/spare#190]
Remove tabs and show all items at once.
<img width="432" alt="screen shot 2018-12-17 at 8 10 52 pm" src="https://user-images.githubusercontent.com/45021523/50131637-f944c000-0237-11e9-8a96-122e7a259067.png">
<img width="432" alt="screen shot 2018-12-17 at 8 10 40 pm" src="https://user-images.githubusercontent.com/45021523/50131639-fa75ed00-0237-11e9-9611-eec9254e7700.png">

Update copy on donor page
```
Select the gently used or new items you can give to those in need.
All hygiene items must be new.
```

Update copy on requestor page

```
Select up to 3 items you need.
```

**Comment by jimthoburn** [comment]
We might also need to change the way Spare works, so that you can request or donate up to 3 items.

I made a separate issue for that part: https://github.com/hackforla/spare/issues/196
