### ISSUE TITLE
Move navigation from bottom to top right

### ISSUE THREAD

**Issue by pmfabel** [hackforla/spare#192]
<img width="432" alt="screen shot 2018-12-17 at 8 16 17 pm" src="https://user-images.githubusercontent.com/45021523/50131802-c2bb7500-0238-11e9-913c-f2b3079416b3.png">
<img width="510" alt="screen shot 2018-12-17 at 8 15 47 pm" src="https://user-images.githubusercontent.com/45021523/50131805-c51dcf00-0238-11e9-8179-02d835361b4c.png">

**Comment by jimthoburn** [comment]
It looks like we’ll also need to move the logo to the top left corner.
