### ISSUE TITLE
Allow users to select up to 3 items when donating and requesting

### ISSUE THREAD

**Issue by jimthoburn** [hackforla/spare#196]
Here’s a related issue:
https://github.com/hackforla/spare/issues/190

Let’s change the request and donate pages so that a visitor can select up to three items to request or donate.

**Comment by jimthoburn** [comment]
@pmfabel do you have thoughts about how the list of items and the form should look while someone is choosing a few items to request? At the moment, if you press an item the form appears, and the item you chose appears in the title.

<img width="1058" alt="form" src="https://user-images.githubusercontent.com/926616/50812878-482ac600-12c9-11e9-8a96-98ef97539e68.png">

**Comment by haydenbetts** [comment]
I'm working on this one on the `feature/196` branch. It is a pretty significant change that looks like it requires both front-end and back-end work. Will post updates here/possibly break up into smaller issues.

**Comment by calexity** [comment]
@haydenbetts excellent - it seems like it might need more product/design direction - do you feel clear on what you're going to do? would you like to chat about it over Slack or at hack night?

**Comment by shawnadelic** [comment]
Closing this for now, since we're implementing this slightly different
