### ISSUE TITLE
Front End - Add styling

### ISSUE THREAD

**Issue by shawnadelic** [hackforla/spare#20]
https://projects.invisionapp.com/share/YKH1L8TAB56#/screens/291938149

Styling for various components should be set up

**TODO:** Break this into multiple issues

**Comment by jrkoch** [comment]
Hi! I can help out with this one

**Comment by shawnadelic** [comment]
@jrkoch Awesome, feel free to contribute!

I believe we're using some version of Bootstrap for React, although I'm not 100% sure about the state of that.

Basically, anything to help our interface look more like the prototype would be helpful.

I might try to break this into smaller tasks if possible as well.

**Comment by jrkoch** [comment]
Cool! I've got it up and running locally and I'm seeing some nice hotly-reloaded changes, so I'll see what I can do.

**Comment by jrkoch** [comment]
PR #51 resolves this issue for existing components accessible from the home page.
