### ISSUE TITLE
DevOps - Set up staging server (Heroku, etc.)

### ISSUE THREAD

**Issue by shawnadelic** [hackforla/spare#25]

**Comment by shawnadelic** [comment]
@mfgryan Assigning this to you since I think you were working on this yesterday (hope that's okay)

**Comment by shawnadelic** [comment]
Assigning this to myself since I've been working on it

**Comment by wlaoh** [comment]
Offering up my personal aws account to host the staging site.  Getting this set up right now.  For now I'm manually pulling the docker images onto the EC2 instance using docker-compose run on the VM.  I've already set up two ECR's for our images (server, client).

I'll get everyone set up with IAM roles so they can access the necessary resources.
