### ISSUE TITLE
Design - Add hover to show how many requests there are

### ISSUE THREAD

**Issue by calexity** [hackforla/spare#29]
Add a hover state on the tiles that shows how many requests there are for each type of item

**Comment by shawnadelic** [comment]
Not sure if this is just a "design" task, but I can implement this on our client (probably using [React Popper](https://www.npmjs.com/package/react-popper) and we can adjust the design if needed.

**Comment by calexity** [comment]
Added this here: https://projects.invisionapp.com/share/HXKT18M6P3M#/screens/302781002
Go to Inspect mode to see any details of the design
