### ISSUE TITLE
Front End: Connect "Contact" to our email address

### ISSUE THREAD

**Issue by shawnadelic** [hackforla/spare#49]
This is a little dependent on this design task (https://github.com/hackforla/spare/issues/44), but we could at least get one set up for now (I believe there is already a route set up).

**Comment by calexity** [comment]
This can just be a mailto:team@whatcanyouspare.org cc @ultraturtle0

**Comment by Allicolyer** [comment]
I can work on figuring out a contact form.

**Comment by calexity** [comment]
Awesome @Allicolyer - I think we can actually just connect it as a link that opens your email client. But if you want to do a contact form, I'm open to that and I can get you a design.

**Comment by calexity** [comment]
@mfgryan did this and it's perfect 💯 ✉️
