### ISSUE TITLE
Back End: Figure out more secure way to generate tokens/codes for donation requests

### ISSUE THREAD

**Issue by shawnadelic** [hackforla/spare#52]
Codes are generated from list of hard-coded words. For better security, we should maybe create a new private, word list (kept out of version control) to be read at runtime, and maybe look at adding further security measures.

**Comment by wlaoh** [comment]
@shawnadelic How about 100% randomly generated nouns?  Here's the output from some trials using Faker:

<img width="168" alt="screen shot 2018-07-31 at 8 00 56 pm" src="https://user-images.githubusercontent.com/8218320/43498635-a89480d0-94fc-11e8-9405-7918866fc1c2.png">
<img width="129" alt="screen shot 2018-07-31 at 8 01 52 pm" src="https://user-images.githubusercontent.com/8218320/43498641-abb2aba2-94fc-11e8-947a-6b9dde4ae844.png">

I think we completely randomly generated slugs, we'll significantly increase the entropy of the words, which should better prevent slug guessing and slug overlap.  It'll also be a much easier form of maintenance.  What do you think?

**Comment by shawnadelic** [comment]
I kind of like this approach. Will definitely think about it.

Also, I'm rethinking the utility of the codes in general right now (I still think they would be useful, and we can still make security improvements for now, but maybe better left off of the frontend until we know they are for sure needed and how they will be used).

Will figure this out this Tuesday.

**Comment by shawnadelic** [comment]
So we talked about this, and it sounds like we'll probably table access codes for phase 1, since it's not clear exactly the best use case for this. I'll add a separate ticket to disable to end point for viewing these for now, just in case.
