### ISSUE TITLE
Front End: Handle sizes on request submission

### ISSUE THREAD

**Issue by shawnadelic** [hackforla/spare#58]
We probably don't want to show the size option for all categories when making donation requests.

Ideally, with things like soap, shampoo, etc, the size field should be hidden by default. 

We can also restrict sizes based on what type of item (dropdown for S, M, L, XL, XXL, etc.), or we may want to leave it blank for now.

I think will probably involve some changes to constants.js. At the very least, we will need to add a `allowSizes` boolean to our itemInfo objects. If we want to have pre-defined sizes, we will also need to hardcode those somewhere.

**Comment by mfgryan** [comment]
addressed here 
https://github.com/hackforla/spare/issues/76
