### ISSUE TITLE
Back End: Add model for drop off times/locations

### ISSUE THREAD

**Issue by shawnadelic** [hackforla/spare#68]
We probably want to be able to support adding/removing different drop-off times and locations. Probably on the backend since we wouldn't want this hardcode on the frontend.

Not 100% sure how this should work right now, but would probably need the following fields at least:

organization_name
location_name
neighborhood
street address 1
street address 2
city
state
zip
neighborhood
phone
website
frequency (maybe just hardcode weekly for now)
dropoff_times
unavailable_times

dropoff_times will probably relate to another model that stores a time or time range within the week (not a specific date) and would look something like:

date (Monday, Tuesday, etc.)
time (12:00pm), or maybe this would be a start/end time range

We will also probably need a model to store dates to skip or make unavailable (for example, holidays). Not sure exactly how this should be stored.

Neighborhood will be a foreign key to a Neighborhood model, to make requesting as easy as possible.

A link to Google Maps directions or something might be useful too.

All upcoming and available meetup times (within the next 2 weeks) would be exposed via an endpoint that would be fetched by client in order to render the options within the form.

**Comment by calexity** [comment]
@shawnadelic thank you for this 🙌 - I added phone + website to you list above as I think we'll want to pull that into the email

**Comment by wlaoh** [comment]
Can we close this?
