### ISSUE TITLE
Front End: Add hover to header and confirmation buttons

### ISSUE THREAD

**Issue by calexity** [hackforla/spare#71]
Add hover state to 
1) top CTAs (request + donate)
2) confirmation CTAs (request + donate)

Hover state is reverse of button's default state. For example:
- Brown background button becomes white background with border and colored text

**Comment by Allicolyer** [comment]
This is an open pull request for this.

**Comment by jrkoch** [comment]
I'll merge the PR @Ozymandias9000 (thanks!)
