### ISSUE TITLE
Request an item functionality does not work as intended

### ISSUE THREAD

**Issue by haydenbetts** [hackforla/spare#74]
Here is how the request an item workflow works for 'cat food'
1. User attempts to request Cat Food.
2. The following form appears:
![cat_food](https://user-images.githubusercontent.com/2898213/41950683-0b898be6-797c-11e8-81aa-362c46e67056.png)

Currently, the requested item value that this form submits is (#2) - "Shoes", the value in the drop down.
The user expects this form to submit #1 - "Cat Food"

Per @calexity, the form field listed in #2 should not exist. This drop down should not designate the type of requested item.

**Comment by mfgryan** [comment]
working on this
