### ISSUE TITLE
Front End: Replace "city" field in Request form with dropdown Neighborhood menu

### ISSUE THREAD

**Issue by ultraturtle0** [hackforla/spare#79]
We currently have a "city" field in the Request form which needs to be replaced with a list of Neighborhoods, to make requesting nearby locations as easy as possible.

**Comment by calexity** [comment]
Neighborhoods can be:

Boyle Heights
Highland Park
Silver Lake

**Comment by jrkoch** [comment]
Looks like this is done -- closing
