### ISSUE TITLE
Add validation for Phone Numbers 

### ISSUE THREAD

**Issue by calexity** [hackforla/spare#92]
- Autoformat phone number like (xxx) xxx-xxxx
- Accept ten digits

**Comment by Allicolyer** [comment]
Example of phone number validator 

validators': [
                # Valid formats:
                #     123-123-1234
                #     123 123-1234
                #     (123)123-1234
                #     (123) 123-1234
                #     (123)-123-1234
                RegexValidator(
                    '^\(?\d{3}\)?\s?-?\d{3}-?\d{4}$',
                    message='Invalid phone number.',
                    code='invalid_phone_number',
                )

**Comment by Allicolyer** [comment]
See Shawn's pull request.
