### ISSUE TITLE
Copy - Email (Donor) - Reminder that donation is coming up

### ISSUE THREAD

**Issue by calexity** [hackforla/spare#97]
Copy for email reminding the donor their donation is coming up

Should be similar to initial confirmation but subject mention it is a reminder

**Comment by haydenbetts** [comment]
Claim

**Comment by calexity** [comment]
@haydenbetts when you're done with the copy for this one, can you include it in this ticket? https://github.com/hackforla/spare/issues/98

**Comment by haydenbetts** [comment]
Finished! Added copy to #98 !

**Comment by calexity** [comment]
@haydenbetts Perfect 🙌 🙌 🙌  Thank you. Closing this.
