### ISSUE TITLE
Copy - Email (Donor) - Did you drop off the item

### ISSUE THREAD

**Issue by calexity** [hackforla/spare#99]
Copy for email confirming donor dropped off item.

Could include:
- Question "Did you drop off the item?"
- Possible answers "Yes, No, Left at the site, Need to reschedule"
- Include our contact info

**Comment by haydenbetts** [comment]
Claim

**Comment by calexity** [comment]
@haydenbetts are you picking these up? I assigned them to you JIC

**Comment by calexity** [comment]
@haydenbetts when you write this one, can you include in this issue?
https://github.com/hackforla/spare/issues/100

**Comment by haydenbetts** [comment]
Finished! Added email copy to #100 !

**Comment by calexity** [comment]
@haydenbetts you're the best. Thank you. Closing this.
